apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service
  labels:
    app: price-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-service
  template:
    metadata:
      labels:
        app: price-service
    spec:
      containers:
      - name: price-service
        image: amodgupta/polydemo:price-service
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: price-service
  name: price-service
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    app: price-service
status:
  loadBalancer: {}
